    <div class="widget-similar-products">
        <h2><?php echo __('Проданы сегодня'); ?></h2>
        <ul class="product-items">
            <?php foreach ($this->getSimilarProducts() as $product): ?>
                <li class="product-item">
                    <a href="<?php echo $product->getProductUrl(); ?>"><?php echo $product->getName(); ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
