<?php
/** @var $block \Magento\Framework\View\Element\Template */
/**@var \Perspective\Orders\ViewModel\Order $viewModel*/

$viewModel = $block->getData('order_view_model');

$getOrders = $viewModel->getOrders();
foreach ($getOrders as $order) {
?>
    <h1><b><?= $order->getId() ?></b>. <?= $order->getCustomerName() ?></h1>
    <?php
        foreach($order->getItems() as $item){
            ?>
            <h3><?= $item->getId() ?>. <?= $item->getName() ?></h3>
            <?php
        }
    ?>

    <hr>
<?php
}
?>
